---
- name: Create TLS Dir
  file:
    path: "{{ vault_tls_dir }}"
    state: directory

- name: Copy Certificate
  copy:
    src: "{{ vault_tls_src_cert_file }}"
    dest: "{{ vault_tls_cert_file }}"

- name: Copy Private Key
  copy:
    src: "{{ vault_tls_src_key_file }}"
    dest: "{{ vault_tls_key_file }}"

- name: Copy Root CA
  copy:
    src: "{{ vault_tls_src_ca_file }}"
    dest: "{{ vault_tls_ca_file }}"
